### ISSUE TITLE
Docker-compose auto import projects

### ISSUE THREAD

**Issue by d4rfl0w** [castlemock/docker#13] opened 2024-04-08 09:30 UTC
Hi,

I have configuration in docker-compose:

```
    mockserver_aggregator:
        image: castlemock/castlemock
        ports:
            - 8080:8080
        volumes:
            - ./_infrastructure/mockserver/.castlemock:/root/.castlemock
```
            
How i can auto import some projects when service start in docker-compose?

**Comment by karldahlgren** [comment] 2024-04-08 21:02
Closing this issue since it is a duplicate of the following issue: https://github.com/castlemock/castlemock/issues/745

**Closed by karldahlgren** 2024-04-08 21:02 UTC
